### ISSUE TITLE
programming-basicsの課題レポジトリ

### ISSUE THREAD

**Issue by kanonnoheya** [MukaiClass/Programming-Basics#3]
先生の講義情報ページの課題ファイルの取得という項目に書いてある通りに、programming-basicsの課題用レポジトリ（課題ファイルのexampleが入っているらしい）にアクセスしてダウンロードしようとしたのですが、見当たりません。どこにアップロードされていますか？それともアップロードはされていないのでしょうか？
スライドを開いて課題を確認しながらやるのが少し大変なのでできればどこにあるのか教えて欲しいです、、。

**Comment by TomohikoMukai** [comment]
そちらの解説ページは今後使用する予定ですが、今回の課題についてはファイルはアップロードしていません。わかりにくくて申し訳ないです。。

**Comment by kanonnoheya** [comment]
わかりました！わざわざありがとうございました！
